#!/bin/bash

echo "deleting topic"
kafka-topics.sh --zookeeper 127.0.0.1:2181 --delete --topic product-ratings
echo "generating stream"
#add data to the product-ratings topic in Kafka
#while read -r line; sleep 1; do echo $line | awk -F'\t' -v OFS='\t' '{print $0}'; done < ./sales_observations | kafka-console-producer.sh --broker-list "localhost:9092" --topic product-ratings
{
  read
  while IFS=, read -r line
  sleep 1
  do 
     echo "$line"
  done
} < ./sales_observations | kafka-console-producer.sh --broker-list "localhost:9092" --topic product-ratings
