#!/bin/bash

cd $HOME
if [ ! -d kafka_2.12-2.5.0 ]; then
   wget http://www.gtlib.gatech.edu/pub/apache/kafka/2.5.0/kafka_2.12-2.5.0.tgz
   tar -xzf kafka_2.12-2.5.0.tgz
   rm kafka_2.12-2.5.0.tgz
fi
cd kafka_2.12-2.5.0

kill $(lsof -i:9092 | grep LISTEN | awk '{print $2}')
kill $(lsof -i:2181 | grep LISTEN | awk '{print $2}')

if [ $(echo $PATH | grep kafka_2.12-2.5.0/bin | wc -l) -lt 1 ]; then
   echo "PATH=\"\$PATH:\$HOME/kafka_2.12-2.5.0/bin\"" >> $HOME/.bashrc
fi

zookeeper-server-start.sh config/zookeeper.properties &
kafka-server-start.sh config/server.properties &

if [ $(kafka-topics.sh --list --bootstrap-server localhost:9092 | grep product-ratings | wc -l) -lt 1 ]; then
   kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic product-ratings
fi
