#!/bin/bash

cd $HOME
if [ ! -d kafka_2.11-2.4.1 ]; then
   wget http://www.gtlib.gatech.edu/pub/apache/kafka/2.4.1/kafka_2.11-2.4.1.tgz 
   tar -xzf kafka_2.11-2.4.1.tgz
   rm kafka_2.11-2.4.1.tgz
fi
cd kafka_2.11-2.4.1

kill $(lsof -i:9092 | grep LISTEN | awk '{print $2}')
kill $(lsof -i:2181 | grep LISTEN | awk '{print $2}')

if [ $(echo $PATH | grep kafka_2.11-2.4.1/bin | wc -l) -lt 1 ]; then
   echo "PATH=\"\$PATH:\$HOME/kafka_2.11-2.4.1/bin\"" >> $HOME/.bashrc
fi

$HOME/kafka_2.11-2.4.1/bin/zookeeper-server-start.sh config/zookeeper.properties &
$HOME/kafka_2.11-2.4.1/bin/kafka-server-start.sh config/server.properties &

if [ $(kafka-topics.sh --list --bootstrap-server localhost:9092 | grep product-ratings | wc -l) -lt 1 ]; then
   $HOME/kafka_2.11-2.4.1/bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic product-ratings
fi
